import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import useSWR from "swr";
import styles from "../styles/Home.module.css";

export default function Home() {
  const fetcher = (url) => fetch(url, { method: "GET" }).then((res) => res.json());

  const { data: jokes, error } = useSWR("/api/jokes", fetcher);
  if (error) return <h1>There was an error</h1>;
  if (!jokes) return <h1>...Loading...</h1>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Joke Hell</h1>

        <div className={styles.grid}>
          {jokes.map((joke) => {
            return (
              <div className={styles.card} key={joke.id}>
                <h2>{joke.text}</h2>
                <hr />
                <p>written by: {joke.author}</p>
                <p>categories: {joke.categories.join(", ")}</p>
              </div>
            );
          })}
        </div>

        <Link href="/createNewJoke">Create a new joke 🃏</Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
